Create a 1D NumPy array with 8 zeros and change the last element to 1.
(Hint: Use np.zeros)

In [22]:
import numpy as np
zeros_array = np.zeros(8)
print(zeros_array)
zeros_array[-1] = 1
print("Changing last value :",zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0.]
Changing last value : [0. 0. 0. 0. 0. 0. 0. 1.]


Generate a 1D array of 5 elements, equally spaced between 10 and 20 (inclusive).
(Hint: Use np.linspace)

In [23]:
arr = np.linspace(10,20,5)
print(arr)

[10.  12.5 15.  17.5 20. ]


Create a 1D array using np.arange starting from 3 to 30 with a step of 3, and then reverse it.
(Hint: Slicing can reverse the array)


In [24]:
arr = np.arange(3,31,3)
print(f"Array : {arr}")
print(f"Reversed array : {arr[::-1]}")

Array : [ 3  6  9 12 15 18 21 24 27 30]
Reversed array : [30 27 24 21 18 15 12  9  6  3]


Given a list my_list = [3, 6, 9, 12], convert it to a NumPy array and multiply each element by 2.

In [25]:
my_list = [3, 6, 9, 12]
numpy_list = np.array(my_list)
print(f"Numpy List : {numpy_list}")
print(f"Multiplied by 2 : {numpy_list * 2}")

Numpy List : [ 3  6  9 12]
Multiplied by 2 : [ 6 12 18 24]


Create an empty 1D array of length 6, and assign values from 0 to 5 using a loop.
(Hint: Use np.empty + loop)

In [26]:
empty_array = np.empty(6 , dtype=int)
print(f"Empty array : {empty_array}")
n = 0
for i in empty_array:
  empty_array[n] = n
  n +=1

print("Updated empty array :",empty_array)

Empty array : [0 1 2 3 4 5]
Updated empty array : [0 1 2 3 4 5]


Use np.ones to create a 1D array of 4 ones and convert the data type to int.
(Hint: Use dtype=int)

In [27]:
ones_array = np.ones(4, dtype = int)
print(f"Array : {ones_array}")

Array : [1 1 1 1]


Create a 1D array from 100 to 200 (not inclusive) with a step of 25 using np.arange. Then, find the mean of the array.

In [28]:
arr = np.arange(100, 200, 25)
print(arr)
print(f"Mean : {arr.mean()}")

[100 125 150 175]
Mean : 137.5


Generate a 1D array of 10 values between 0 and 1 (inclusive), then round all elements to 2 decimal places.

In [29]:
arr = np.linspace(0, 1, 10) # Creates 10 element between 0 and 1
rounded_arr = np.round(arr, 2)
print(f"Original array : {arr}")
print(f"Rouned array : {rounded_arr}")

Original array : [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Rouned array : [0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


Use np.empty to create a 1D array of 4 elements and explain the possible values inside it. Why might they look “random”?

In [30]:
arr = np.empty(4)
# it creates array with 4 allocated memory but doesnot initialize the elements
# its value depends on the data what was stored before in that memory so it looks as random(which are not truely random but, just leftovers)
print(arr)


[4.94e-322 6.18e-322 7.41e-322 8.65e-322]


Combine two 1D arrays: one created using np.ones(3) and the other using np.arange(3). Show the final result.

In [31]:
ones_array = np.ones(3)
arr = np.arange(3)
print(f"Ones array : {ones_array}")
print(f"Arange array : {arr}")
print(f"Result : {ones_array+arr}")

Ones array : [1. 1. 1.]
Arange array : [0 1 2]
Result : [1. 2. 3.]
